site_name: GitOps with ArgoCD Workshop
repo_name: saiyam1814/gitex-workshop
repo_url: https://github.com/saiyam1814/gitex-workshop
site_dir: site

theme:
  name: material
  palette:
    scheme: default
    primary: blue
    accent: cyan

nav:
  - Home: index.md
  - Outline: outline.md

plugins:
  - search