site_name: Gitex Asia 2025 - GitOps with ArgoCD
theme:
  name: material
  palette:
    scheme: default
    primary: indigo
    accent: amber
  features:
    - content.code.copy
nav:
  - Home: index.md
repo_url: https://github.com/saiyam1814/gitex-workshop
repo_name: saiyam1814/gitex-workshop
site_dir: site