name: Build & Publish

on:
  push:
    branches: [ main ]

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'

      - name: Set up ko
        uses: ko-build/setup-ko@v0.14
        with:
          version: v0.14.1

      - name: Log in to GitHub Container Registry
        run: |
          echo "${{ secrets.GITHUB_TOKEN }}" | ko login ghcr.io --username ${{ github.actor }} --password-stdin

      - name: Build & push with ko
        working-directory: app
        env:
          # replace with your GHCR repo, e.g. ghcr.io/loftlabs/workshop-gitex-asia
          KO_DOCKER_REPO: ghcr.io/${{ github.repository }}
          KO_DEFAULT_PLATFORM: linux/amd64,linux/arm64
        run: |
          # publish will build & push; tags: git SHA + latest
          ko publish . --tags "sha-${{ github.sha }},latest"
